sudo: required
os: linux


cache:
  directories:
  - ~/.ccache
  - ~/.pkg-cache

services:
- docker

archlinux:
  mount:
  - ~/.ccache:~/.ccache
  - ~/.pkg-cache:/var/cache/pacman/pkg
  packages:
  # Pacman packages
  - ccache
  - git
  - haveged
  - python
  - python-pip
  - sudo

  before_install:
  # 1.Override `package-cleanup.hook` to preserve cache for travis.
  # 2.Enable ccache
  # 3.Multithreaded build and compress
  # 4.Suppress all gcc warnings
  - |
     sudo mkdir /etc/pacman.d/hooks/
     sudo ln -s /dev/null /etc/pacman.d/hooks/package-cleanup.hook
     sudo sed -i '/^BUILDENV/s/\!ccache/ccache/' /etc/makepkg.conf
     sudo sed -i '/#MAKEFLAGS=/c MAKEFLAGS="-j2"' /etc/makepkg.conf
     sudo sed -i '/^COMPRESSXZ/s/\xz/xz -T 2/' /etc/makepkg.conf
     sudo sed -i '$a   CFLAGS="$CFLAGS -w"'   /etc/makepkg.conf
     sudo sed -i '$a CXXFLAGS="$CXXFLAGS -w"' /etc/makepkg.conf
  script:
  # Here do not make any validation (-n) because it will be done later on in the Ubuntu host directly
  - ./bin/test-install

before_install:
  - sudo apt-get update

install:
  - PATH=$PWD/bin:$PATH

script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - "curl -s https://raw.githubusercontent.com/fsquillace/arch-travis/master/arch-travis.sh | bash"
  - "echo pacman pkg cache size: $(du -h ~/.pkg-cache|cut -f1) in $(ls ~/.pkg-cache|wc -l) files"
  - ls -l

